### ISSUE TITLE
Integrating the voting interface as an iframe in another webpage

### ISSUE THREAD

**Issue by PierreMesure** [StanfordCDT/pb#38]
Hi,

I'm trying to integrate PB Stanford's voting interface as an iframe. What would be the easiest way to do it?

I've tried just adding the URL in an `<iframe>` tag and I'm getting an error with the following message:

> Refused to display url in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by lgelauff** [comment]
We currently don't allow embedding our website as an iframe for security reasons. We don't plan to support it anytime soon. 

Please feel free to reach out via email to chat about what you're trying to achieve and whether there are other methods to achieve the same.
