### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by edwardgalligan** [StanfordCDT/pb#5]
Hi,

I've deployed pb on a local instance for testing, and made some code modifications to get things working fully. I'd love to prepare a PR and push them back here, but I just took a look at the commit history, and the pattern seems like things are being maintained elsewhere and then pushed here periodically (the last commit has over 13,000 changes!).

Is there a canonical repository somewhere elsewhere with a more up-to-date version?

**Comment by StanfordCDT** [comment]
Hi, Thank you so much for your using pb! We'd love to see those modifications. We are sorry for the delay in updating the code. Yes, there is an internal repository where we mainly work on. We will try to phase that out and use this repository as the main repository. Please feel free to submit any PR and don't worry about potential conflicts. We will do our best to merge your changes. Thank you again!

**Comment by mdzhang** [comment]
Any updates on moving to this public repo over the internal one?

**Comment by sukolsak** [comment]
We have moved to this public repo over the internal one. Thank you for all the feedback.
